name: env_hemeroteca-peb
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - tinydb
  - pikepdf
  - pandas
  - numpy
  - jupyterlab
  - matplotlib
  - seaborn
  - plotly
  - unidecode
  - ocrmypdf
  - opencv
  - pypdf2
  - pdfrw
  - typing-extensions
  

