import os
from unittest.mock import CallableMixin

def origem_tif():
    origem_raiz = '/media/hdvm08/bd/002/997/001/tif'
    destino_raiz = '/media/hdvm08/bd/002/997/001/pdf'
    #ocrmypdf.ocr(origem,destino,deskew=True)
    for raiz, dirs, arqs in os.walk(origem_raiz):
        for arq in sorted(arqs):
            if "tif" in arq:
                origem_caminho_tif = os.path.join(raiz, arq)
                if 'page' in arq:
                    nome_arquivo_tif = [x for x in arqs if ('page' in arq) and x.startswith(arq[:-12])] #comprensão de lista
                else:
                    nome_arquivo_tif = [arq]
                erradas = lista_siglas_erradas()
                for index,errada in enumerate(erradas):
                    if errada in origem_caminho_tif:
                        print(index, origem_caminho_tif)



def lista_siglas_erradas():
    return ['UE',
    'Lafer',
    'Empresas',
    'ESPBrasil',
    'VALOR',
    'CUT',
    'Valor',
    'GSP',
    'Tratado',
    'retorno',
    'compra',
    'desconhecido',
    'estadao',
    'clarin',
    'JT',
    'JB',
    'ISTOE',
    'VEJA',
    'DAILYPOST',
    'JBi',
    'JC',
    'ABICOMP',
    'SBPC',
    'valor',
    'EmWall',
    "O'Neill",
    'Bush',
    'EUA',
    'Gigante',
    'VE',
    'Washington',
    'OMC',
    'Brasil',
    'Embaixadora',
    'XXX',
    'OESP',
    'OEA',
    'Collor',
    'visao',
    'C',
    'Gm',
    'Toro',
    'ESO',
    'FL',
    'Menem',
    '16',
    'NG',
    'xxx',
    'EC',
    'B',
    'J',
    'A',
    'GM.tif',
    '02',
    'Eleicoes',
    'ESPQueda',
    'GMNovo',
    'GMVW',
    'page0001.tif',
    '25',
    'GMUm',
    'E',
    'GMUE',
    'TA',
    'Cardoso',
    'Alca',
    'Europeus',
    'ESp',
    'PT',
    'xx',
    'Lula',
    'Acordo',
    'GMAlencar',
    "''Brasil",
    'América',
    'Mercosul',
    'Como',
    'Mudando',
    'O',
    'Porta',
    'Uruguai',
    'Um',
    'Estrutura',
    'Uma',
    'É',
    'Perdas',
    'XX',
    'Atraso',
    "''Acordo",
    'Empresario',
    'Cúpulas',
    'Declaração',
    'globo',
    'ambiente',
    'Chirac',
    'FDS',
    '00',
    '0000',
    'EXAME',
    'SEM',
    'sem',
    'França',
    'oesp',
    'jb',
    'istoé',
    'Pastore',
    'ES',
    'causa',
    'Setúbal',
    'energia',
    'entraremos',
    'Chase',
    'ciência',
    'le',
    '17',
    'Itamaraty',
    'Acordos',
    'Importacao',
    'BID',
    'Regime',
    'OAB',
    'Siderurgicas',
    '1GM',
    'CSN',
    'GMContencioso',
    'BR',
    'Lampreia',
    'Diplomatas',
    'Alheias',
    'Conflito',
    'Industria',
    'Recessao',
    'Site']

def main():
    origem_tif()
    
if __name__ == '__main__':
    main()